"""
alexa_complete_app_to_app — POST /api/v1/alexa/completeAppToApp

Completes the Alexa App-to-App account linking flow.

Flow:
  1. Authenticate the caller via Cognito JWT
  2. Validate the state token (CSRF / replay protection):
       - must exist in DynamoDB
       - must belong to the authenticated userId
       - must not be expired (10-minute window)
       - must have status PENDING (single-use)
  3. Mark the state as USED immediately (before token exchange) to
     prevent a race-condition replay
  4. Retrieve the PKCE code_verifier stored during startAppToApp
  5. Exchange the authorization code with Amazon LWA:
       POST https://api.amazon.com/auth/o2/token
         grant_type    = authorization_code
         code          = <from Flutter>
         redirect_uri  = https://iot.digilux.co.in/alexa/callback
         client_id     = <from Secrets Manager>
         client_secret = <from Secrets Manager>
         code_verifier = <from DynamoDB session>
  6. Store access_token + refresh_token in digilux_honeywell_alexa_lwa_tokens
  7. Return { "linked": true }

Note: The Alexa skill is already enabled by the time this endpoint is called —
the user went through the Alexa consent UI (App-to-App flow) which enables
the skill automatically. No separate SMAPI enablement call is needed.

Error responses:
  400 — invalid/expired/already-used state, missing fields
  401 — unauthenticated
  502 — Amazon token exchange failed
"""
from __future__ import annotations

import base64
import json
import logging
import os
import re
import time
import urllib.error
import urllib.parse
import urllib.request

import boto3

# UUID v4 regex — state must be a valid UUID4 generated by startAppToApp
_UUID4_RE = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
    re.IGNORECASE,
)

logger = logging.getLogger()
logger.setLevel(getattr(logging, os.environ.get("LOG_LEVEL", "INFO").upper(), logging.INFO))

# ── Environment variables ──────────────────────────────────────────────────────
# All values are required unless marked optional.
# Set them as Lambda environment variables (or export them locally).
# See .env.example at the repo root for descriptions of every variable.
_REGION                    = os.environ.get("DATA_REGION",                "")
_SESSION_TABLE             = os.environ.get("SESSION_TABLE",              "")
_TOKENS_TABLE              = os.environ.get("LWA_TOKENS_TABLE",           "")
_USER_DEVICE_MAPPING_TABLE = os.environ.get("USER_DEVICE_MAPPING_TABLE",  "")
_REDIRECT_URI              = os.environ.get("REDIRECT_URI",               "")
_LWA_SECRET_ARN            = os.environ.get("LWA_SECRET_ARN",             "")
_LWA_SECRET_REGION         = os.environ.get("LWA_SECRET_REGION",          "")
_LWA_TOKEN_URL             = os.environ.get("LWA_TOKEN_URL",              "")
_ALEXA_SKILL_ID            = os.environ.get("ALEXA_SKILL_ID",             "")  # for audit logging only
_CREATE_UPDATE_FN          = os.environ.get("CREATE_UPDATE_FN",           "")
_LWA_HTTP_TIMEOUT          = int(os.environ.get("LWA_HTTP_TIMEOUT",            "10"))  # optional
_TOKEN_EXPIRY_BUFFER_S     = int(os.environ.get("TOKEN_EXPIRY_BUFFER_SECONDS",  "60"))  # optional
_KMS_KEY_ARN               = os.environ.get("KMS_KEY_ARN",                    "")
_COGNITO_USER_POOL_ID      = os.environ.get("COGNITO_USER_POOL_ID",           "")
_COGNITO_REGION            = os.environ.get("COGNITO_REGION",                  _REGION or "")
_MAX_REQUEST_BODY_BYTES    = int(os.environ.get("MAX_REQUEST_BODY_BYTES",      "4096"))  # optional
_MAX_AUTH_CODE_LEN         = int(os.environ.get("MAX_AUTH_CODE_LEN",          "2048"))  # optional
_LWA_REVOKE_URL            = os.environ.get("LWA_REVOKE_URL",                 "")
_LWA_PROFILE_URL           = os.environ.get("LWA_PROFILE_URL",
                                             "https://api.amazon.com/user/profile")
_COGNITO_ISSUER = (
    f"https://cognito-idp.{_COGNITO_REGION}.amazonaws.com/{_COGNITO_USER_POOL_ID}"
    if _COGNITO_USER_POOL_ID else ""
)

# ── Startup config validation ──────────────────────────────────────────────────
_REQUIRED_VARS = {
    "DATA_REGION":         _REGION,
    "SESSION_TABLE":       _SESSION_TABLE,
    "LWA_TOKENS_TABLE":    _TOKENS_TABLE,
    "REDIRECT_URI":        _REDIRECT_URI,
    "LWA_SECRET_ARN":      _LWA_SECRET_ARN,
    "LWA_SECRET_REGION":   _LWA_SECRET_REGION,
    "LWA_TOKEN_URL":       _LWA_TOKEN_URL,
}
_missing_vars = [k for k, v in _REQUIRED_VARS.items() if not v]
if _missing_vars:
    logger.error("CONFIG_STARTUP_ERROR missing_required_env=%s — "
                 "invocations will return HTTP 500", _missing_vars)

# ── Startup security warnings ──────────────────────────────────────────────────
if not _COGNITO_USER_POOL_ID:
    logger.warning("SECURITY_WARNING COGNITO_USER_POOL_ID not set — "
                   "JWT signature verification DISABLED (set for production)")
if not _KMS_KEY_ARN:
    logger.warning("SECURITY_WARNING KMS_KEY_ARN not set — "
                   "tokens stored in plaintext (set for production)")
if not _LWA_REVOKE_URL:
    logger.warning("SECURITY_WARNING LWA_REVOKE_URL not set — "
                   "token revocation on unlink will be unavailable")

# Module-level caches
_dynamodb        = None
_lwa_creds: tuple[str, str] | None = None
_kms_cache       = None
_jwks_cache: dict | None = None
_lambda_client   = None


def _ddb():
    global _dynamodb
    if _dynamodb is None:
        logger.debug("DDB_INIT region=%s (cold start)", _REGION)
        _dynamodb = boto3.resource("dynamodb", region_name=_REGION)
    else:
        logger.debug("DDB_REUSE region=%s (warm container)", _REGION)
    return _dynamodb


def _get_lwa_creds() -> tuple[str, str]:
    """Load LWA client_id + client_secret from Secrets Manager (cached per container)."""
    global _lwa_creds
    if _lwa_creds is None:
        logger.info("SECRETS_FETCH arn=%s region=%s (cold start)", _LWA_SECRET_ARN, _LWA_SECRET_REGION)
        sm  = boto3.client("secretsmanager", region_name=_LWA_SECRET_REGION)
        raw = sm.get_secret_value(SecretId=_LWA_SECRET_ARN)["SecretString"]
        d   = json.loads(raw)
        _lwa_creds = d["client_id"], d["client_secret"]
        logger.info("SECRETS_LOADED client_id_prefix=%s", d["client_id"][:6])
    else:
        logger.debug("SECRETS_CACHED (warm container, skipping Secrets Manager call)")
    return _lwa_creds


def _kms():
    global _kms_cache
    if _kms_cache is None:
        logger.debug("KMS_INIT region=%s (cold start)", _REGION)
        _kms_cache = boto3.client("kms", region_name=_REGION)
    return _kms_cache


def _encrypt_field(plaintext: str) -> str:
    """KMS-encrypt a string and return base64-encoded ciphertext.
    Returns plaintext unchanged if KMS_KEY_ARN is not configured."""
    if not _KMS_KEY_ARN:
        return plaintext
    response = _kms().encrypt(KeyId=_KMS_KEY_ARN, Plaintext=plaintext.encode())
    return base64.b64encode(response["CiphertextBlob"]).decode()


def _decrypt_field(value: str) -> str:
    """Decrypt a KMS-encrypted base64 string back to plaintext.
    Returns value unchanged if KMS_KEY_ARN is not configured."""
    if not _KMS_KEY_ARN:
        return value
    ciphertext = base64.b64decode(value.encode())
    response   = _kms().decrypt(CiphertextBlob=ciphertext)
    return response["Plaintext"].decode()


def _get_jwks() -> dict:
    """Fetch and cache the Cognito JWKS for JWT signature verification."""
    global _jwks_cache
    if _jwks_cache is None:
        url = f"{_COGNITO_ISSUER}/.well-known/jwks.json"
        logger.debug("JWKS_FETCH url=%s", url)
        with urllib.request.urlopen(url, timeout=5) as r:
            _jwks_cache = json.loads(r.read())
        logger.info("JWKS_LOADED key_count=%d", len(_jwks_cache.get("keys", [])))
    else:
        logger.debug("JWKS_CACHED")
    return _jwks_cache


def _verify_jwt_signature(token: str) -> None:
    """Verify the JWT RS256 signature against Cognito JWKS (defense-in-depth).
    No-op if COGNITO_USER_POOL_ID is not set. Raises ValueError if invalid."""
    if not _COGNITO_USER_POOL_ID:
        logger.warning("JWT_VERIFY_SKIPPED COGNITO_USER_POOL_ID not configured")
        return
    try:
        from jose import jwt as jose_jwt
    except ImportError:
        logger.error("JWT_VERIFY_UNAVAILABLE python-jose not installed — "
                     "add python-jose[cryptography] to requirements.txt")
        return
    try:
        parts   = token.split(".")
        padding = "=" * (4 - len(parts[0]) % 4)
        header  = json.loads(base64.urlsafe_b64decode(parts[0] + padding))
        kid     = header.get("kid", "")
        jwks    = _get_jwks()
        key     = next((k for k in jwks.get("keys", []) if k.get("kid") == kid), None)
        if not key:
            raise ValueError(f"JWT kid='{kid}' not found in JWKS")
        jose_jwt.decode(
            token, key,
            algorithms=["RS256"],
            issuer=_COGNITO_ISSUER,
            options={"verify_at_hash": False},
        )
        logger.debug("JWT_SIGNATURE_VERIFIED kid=%s", kid)
    except Exception as exc:
        logger.warning("JWT_SIGNATURE_INVALID reason=%s", exc)
        raise ValueError(f"JWT signature invalid: {exc}") from exc


def _decode_jwt_sub(token: str) -> str:
    parts = token.split(".")
    if len(parts) != 3:
        logger.debug("JWT_INVALID part_count=%d expected=3", len(parts))
        raise ValueError(f"JWT has {len(parts)} parts, expected 3")
    padding = "=" * (4 - len(parts[1]) % 4)
    try:
        claims = json.loads(base64.urlsafe_b64decode(parts[1] + padding))
    except Exception as exc:
        logger.debug("JWT_DECODE_FAILED reason=%s", exc)
        raise ValueError(f"Could not decode JWT payload: {exc}") from exc
    sub = claims.get("sub") or claims.get("username")
    if not sub:
        logger.debug("JWT_MISSING_SUB available_claims=%s", list(claims.keys()))
        raise ValueError("Missing sub/username claim in JWT")
    claim_source = "sub" if claims.get("sub") else "username"
    logger.debug("JWT_DECODED claim_source=%s", claim_source)
    return sub


def _exchange_code(code: str, code_verifier: str) -> dict:
    """
    Exchange an authorization code for LWA access + refresh tokens using PKCE.
    Raises RuntimeError on non-2xx response from Amazon.
    """
    client_id, client_secret = _get_lwa_creds()

    logger.debug("LWA_EXCHANGE_START endpoint=%s code_prefix=%s verifier_len=%d",
                 _LWA_TOKEN_URL, code[:6], len(code_verifier))

    data = urllib.parse.urlencode({
        "grant_type":    "authorization_code",
        "code":          code,
        "redirect_uri":  _REDIRECT_URI,
        "client_id":     client_id,
        "client_secret": client_secret,
        "code_verifier": code_verifier,
    }).encode()

    req = urllib.request.Request(
        _LWA_TOKEN_URL,
        data=data,
        headers={"Content-Type": "application/x-www-form-urlencoded"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=_LWA_HTTP_TIMEOUT) as r:
            response_body = r.read()
            logger.debug("LWA_EXCHANGE_RESPONSE status=200 body_len=%d", len(response_body))
            return json.loads(response_body)
    except urllib.error.HTTPError as e:
        err = e.read().decode(errors="replace")
        logger.error("LWA_EXCHANGE_HTTP_ERROR status=%d body=%s", e.code, err)
        raise RuntimeError(f"LWA token exchange failed HTTP {e.code}: {err}") from e


def _get_amazon_user_id(access_token: str) -> str | None:
    """
    Call the Amazon LWA Profile API to get the stable Amazon user ID.
    This ID is stored in DynamoDB so that the alexa_skill_events Lambda
    can look up the Cognito userId when Alexa sends a SkillDisabled event.
    Returns None on failure — best-effort, does not block linking.
    """
    req = urllib.request.Request(
        _LWA_PROFILE_URL,
        headers={"Authorization": f"Bearer {access_token}"},
        method="GET",
    )
    try:
        with urllib.request.urlopen(req, timeout=_LWA_HTTP_TIMEOUT) as r:
            profile = json.loads(r.read())
        amazon_user_id = profile.get("user_id", "")
        logger.debug("LWA_PROFILE_OK user_id_prefix=%s", amazon_user_id[:12] if amazon_user_id else "none")
        return amazon_user_id or None
    except Exception as exc:
        logger.warning("LWA_PROFILE_ERROR error=%s — amazonUserId will not be stored", exc)
        return None


def _notify_alexa_enabled(user_id: str, site_id: str, is_enabled: bool) -> None:
    """
    Async fire-and-forget: tell create_and_update_data_function to set
    isAlexaEnabled on the site record and user data table.
    Non-fatal — failure is logged, linking is already complete.
    """
    if not _CREATE_UPDATE_FN or not site_id:
        return
    global _lambda_client
    if _lambda_client is None:
        _lambda_client = boto3.client("lambda", region_name=_REGION)
    payload = json.dumps({
        "_source":        "alexa_internal",
        "userId":         user_id,
        "siteId":         site_id,
        "isAlexaEnabled": is_enabled,
    }).encode()
    try:
        _lambda_client.invoke(
            FunctionName=_CREATE_UPDATE_FN,
            InvocationType="Event",   # async — does not block response
            Payload=payload,
        )
        logger.info("ALEXA_ENABLED_NOTIFY_SENT fn=%s userId=%s siteId=%s isAlexaEnabled=%s",
                    _CREATE_UPDATE_FN, user_id, site_id, is_enabled)
    except Exception as exc:
        logger.warning("ALEXA_ENABLED_NOTIFY_FAILED fn=%s userId=%s siteId=%s error=%s",
                       _CREATE_UPDATE_FN, user_id, site_id, exc)


def lambda_handler(event, context):  # noqa: ANN001
    request_id = getattr(context, "aws_request_id", "local")
    logger.info("REQUEST_START function=completeAppToApp request_id=%s", request_id)

    # ── 0. Guard: fail fast if required env vars are missing ──────────────────
    if _missing_vars:
        logger.error("CONFIG_ERROR missing=%s request_id=%s", _missing_vars, request_id)
        return _resp(500, {"error": "Server configuration error"})

    # ── 1. Authenticate ───────────────────────────────────────────────────────
    headers = event.get("headers") or {}
    auth    = headers.get("Authorization") or headers.get("authorization") or ""

    if not auth:
        logger.warning("AUTH_MISSING no Authorization header request_id=%s", request_id)
        return _resp(401, {"error": "Unauthorized"})

    scheme = auth.split(" ")[0] if " " in auth else auth
    logger.debug("AUTH_HEADER_PRESENT scheme=%s request_id=%s", scheme, request_id)

    token = auth.split(" ")[-1].strip()

    try:
        _verify_jwt_signature(token)          # defense-in-depth RS256 check
        user_id = _decode_jwt_sub(token)
        logger.info("AUTH_OK userId=%s request_id=%s", user_id, request_id)
    except Exception as exc:
        logger.warning("AUTH_FAILED reason=%s request_id=%s", exc, request_id)
        return _resp(401, {"error": "Unauthorized"})

    # ── 2. Parse + validate request body ─────────────────────────────────────
    raw_body = event.get("body") or ""
    if len(raw_body) > _MAX_REQUEST_BODY_BYTES:
        logger.warning("BODY_TOO_LARGE size=%d max=%d userId=%s request_id=%s",
                       len(raw_body), _MAX_REQUEST_BODY_BYTES, user_id, request_id)
        return _resp(400, {"error": "Request body too large"})

    logger.debug("BODY_PARSE_START request_id=%s", request_id)
    try:
        body    = json.loads(raw_body or "{}")
        code    = str(body.get("code",    "")).strip()
        state   = str(body.get("state",   "")).strip()
        site_id = str(body.get("siteId",  "")).strip()
    except (json.JSONDecodeError, TypeError) as exc:
        logger.warning("BODY_PARSE_FAILED reason=%s request_id=%s", exc, request_id)
        return _resp(400, {"error": "Invalid JSON body"})

    if not code:
        logger.warning("BODY_MISSING_FIELD field=code userId=%s request_id=%s",
                       user_id, request_id)
        return _resp(400, {"error": "code is required"})
    if not state:
        logger.warning("BODY_MISSING_FIELD field=state userId=%s request_id=%s",
                       user_id, request_id)
        return _resp(400, {"error": "state is required"})

    if not _UUID4_RE.match(state):
        logger.warning("STATE_INVALID_FORMAT state=%s userId=%s request_id=%s",
                       state, user_id, request_id)
        return _resp(400, {"error": "Invalid state format"})

    if len(code) > _MAX_AUTH_CODE_LEN:
        logger.warning("CODE_TOO_LONG code_len=%d max=%d userId=%s request_id=%s",
                       len(code), _MAX_AUTH_CODE_LEN, user_id, request_id)
        return _resp(400, {"error": "Invalid authorization code"})

    logger.debug("BODY_PARSED userId=%s state=%s code_prefix=%s request_id=%s",
                 user_id, state, code[:6], request_id)

    session_table = _ddb().Table(_SESSION_TABLE)

    # ── 3. Validate state ─────────────────────────────────────────────────────
    logger.debug("SESSION_LOOKUP table=%s state=%s userId=%s request_id=%s",
                 _SESSION_TABLE, state, user_id, request_id)

    result  = session_table.get_item(Key={"state": state})
    session = result.get("Item")

    if not session:
        logger.warning("SESSION_NOT_FOUND state=%s userId=%s request_id=%s",
                       state, user_id, request_id)
        return _resp(400, {"error": "Invalid state"})

    logger.debug("SESSION_FOUND state=%s status=%s owner=%s created_at=%s expires_at=%s request_id=%s",
                 state, session.get("status"), session.get("userId"),
                 session.get("createdAt"), session.get("expiresAt"), request_id)

    if session.get("userId") != user_id:
        logger.warning(
            "SESSION_OWNER_MISMATCH state=%s session_owner=%s requester=%s request_id=%s",
            state, session.get("userId"), user_id, request_id,
        )
        return _resp(400, {"error": "Invalid state"})

    now = int(time.time())
    if int(session.get("expiresAt", 0)) < now:
        age_seconds = now - int(session.get("createdAt", now))
        logger.warning(
            "SESSION_EXPIRED state=%s userId=%s age_seconds=%d request_id=%s",
            state, user_id, age_seconds, request_id,
        )
        return _resp(400, {"error": "Linking session expired — please start again"})

    if session.get("status") != "PENDING":
        logger.warning(
            "SESSION_ALREADY_USED state=%s status=%s userId=%s used_at=%s request_id=%s",
            state, session.get("status"), user_id, session.get("usedAt"), request_id,
        )
        return _resp(400, {"error": "Session already used"})

    code_verifier = _decrypt_field(session.get("codeVerifier", ""))
    session_age   = now - int(session.get("createdAt", now))
    logger.info("SESSION_VALID state=%s userId=%s age_seconds=%d request_id=%s",
                state, user_id, session_age, request_id)

    # ── 4. Mark state USED immediately (before network call — prevents replay) ─
    used_at = int(time.time())
    logger.debug("SESSION_MARK_USED state=%s userId=%s used_at=%d request_id=%s",
                 state, user_id, used_at, request_id)

    session_table.update_item(
        Key={"state": state},
        UpdateExpression="SET #st = :used, usedAt = :ts",
        ExpressionAttributeNames={"#st": "status"},
        ExpressionAttributeValues={":used": "USED", ":ts": used_at},
    )

    # AUDIT — replay protection: state is now single-use
    logger.info(
        "[AUDIT] SESSION_USED state=%s userId=%s used_at=%d session_age_seconds=%d request_id=%s",
        state, user_id, used_at, session_age, request_id,
    )

    # ── 5. Exchange authorization code with Amazon ────────────────────────────
    logger.info("LWA_EXCHANGE userId=%s state=%s endpoint=%s request_id=%s",
                user_id, state, _LWA_TOKEN_URL, request_id)
    try:
        tokens = _exchange_code(code, code_verifier)
    except RuntimeError as exc:
        logger.error("LWA_EXCHANGE_FAILED userId=%s state=%s error=%s request_id=%s",
                     user_id, state, exc, request_id)
        return _resp(502, {"error": "Failed to complete Alexa account linking"})

    access_token  = tokens.get("access_token",  "")
    refresh_token = tokens.get("refresh_token", "")
    expires_in    = int(tokens.get("expires_in", 3600))
    token_type    = tokens.get("token_type", "unknown")
    expires_at    = int(time.time()) + expires_in - _TOKEN_EXPIRY_BUFFER_S

    logger.info(
        "LWA_EXCHANGE_OK userId=%s state=%s token_type=%s expires_in=%d expires_at=%d request_id=%s",
        user_id, state, token_type, expires_in, expires_at, request_id,
    )

    # ── 6. Store tokens in LWA table ──────────────────────────────────────────
    linked_at = int(time.time())

    # Fetch Amazon user ID for reverse-lookup when Alexa sends SkillDisabled events
    amazon_user_id = _get_amazon_user_id(access_token)
    if amazon_user_id:
        logger.info("AMAZON_USER_ID_FETCHED userId=%s amazon_user_id_prefix=%s request_id=%s",
                    user_id, amazon_user_id[:12], request_id)
    else:
        logger.warning("AMAZON_USER_ID_MISSING userId=%s — SkillDisabled events cannot be "
                       "mapped to this user request_id=%s", user_id, request_id)

    logger.debug("TOKEN_STORE_START table=%s userId=%s expires_at=%d request_id=%s",
                 _TOKENS_TABLE, user_id, expires_at, request_id)

    token_item: dict = {
        "userId":       user_id,
        "accessToken":  _encrypt_field(access_token),
        "refreshToken": _encrypt_field(refresh_token),
        "expiresAt":    expires_at,
        "linkedAt":     linked_at,
        "linkMethod":   "app-to-app",
    }
    if amazon_user_id:
        token_item["amazonUserId"] = amazon_user_id

    _ddb().Table(_TOKENS_TABLE).put_item(Item=token_item)

    logger.debug("TOKEN_STORE_OK table=%s userId=%s request_id=%s",
                 _TOKENS_TABLE, user_id, request_id)

    # ── 6b. Update per-site linked flag in user-device mapping table ─────────
    if site_id and _USER_DEVICE_MAPPING_TABLE:
        logger.info("SITE_LINK_UPDATE table=%s userId=%s siteId=%s request_id=%s",
                    _USER_DEVICE_MAPPING_TABLE, user_id, site_id, request_id)
        try:
            _ddb().Table(_USER_DEVICE_MAPPING_TABLE).update_item(
                Key={"userId": user_id, "siteId": site_id},
                UpdateExpression="SET alexaLinked = :t, alexaLinkedAt = :ts",
                ExpressionAttributeValues={":t": True, ":ts": linked_at},
            )
            logger.info("SITE_LINK_UPDATE_OK userId=%s siteId=%s request_id=%s",
                        user_id, site_id, request_id)
        except Exception as exc:
            logger.error("SITE_LINK_UPDATE_FAILED userId=%s siteId=%s error=%s request_id=%s",
                         user_id, site_id, exc, request_id)
    elif site_id:
        logger.warning("SITE_LINK_UPDATE_SKIPPED USER_DEVICE_MAPPING_TABLE not configured "
                       "userId=%s siteId=%s request_id=%s", user_id, site_id, request_id)

    # AUDIT — full account linking completed
    logger.info(
        "[AUDIT] ACCOUNT_LINKED userId=%s siteId=%s state=%s skill_id=%s "
        "link_method=app-to-app linked_at=%d token_expires_at=%d request_id=%s",
        user_id, site_id or "none", state, _ALEXA_SKILL_ID,
        linked_at, expires_at, request_id,
    )

    # ── 6c. Notify create_and_update_data_function to set isAlexaEnabled=true ─
    _notify_alexa_enabled(user_id, site_id, True)

    # ── 7. Return success ─────────────────────────────────────────────────────
    logger.info("REQUEST_OK function=completeAppToApp userId=%s state=%s request_id=%s",
                user_id, state, request_id)
    return _resp(200, {"linked": True})


def _resp(status_code: int, body: dict) -> dict:
    return {
        "statusCode": status_code,
        "headers":    {"Content-Type": "application/json", "Access-Control-Allow-Origin": "*"},
        "body":       json.dumps(body),
    }
